name = "ReplaceLibstdcxx"
uuid = "888ffc4c-e7a9-4266-b690-ff1da87a7386"
authors = ["Helmut Hänsel <helmut.haensel@gmx.de>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[deps]
JSON = "0.20, 0.21"